name: CI

on:
  push:
    branches:
      - carrie  # or your default branch
  pull_request:
    branches:
      - master  # or your default branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version you are using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas snowflake-connector-python pyyaml

    - name: Run tests
      run: |
        python -m unittest discover -s . -p "test_*.py"

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          **/test_*.xml
